/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package snake;

import java.awt.event.KeyEvent;

/**
 *
 * @author Miguel Zamorano
 */
public class frmSnake extends javax.swing.JFrame implements java.awt.event.KeyListener{
    
    Snake snake;
    Opciones opciones;
    /**
     * Creates new form frmSnake
     */
    public frmSnake() {
        initComponents();
        setTitle("El Snake del miguelón");
        snake = new Snake(24, 18, DefSpeed.NORMAL.getS());
        opciones = new Opciones(DefSpeed.NORMAL, 24, 18);
        add(snake);
        setSize(snake.getWidth()+18,snake.getHeight()+60);
        setLocationRelativeTo(null);
        addKeyListener(this);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("Juego");

        jMenuItem1.setText("Opciones");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);
        jMenu1.add(jSeparator1);

        jMenuItem2.setText("Salir");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        dispose();
        System.exit(0);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        Opciones o = new Opciones(opciones);
        int w = o.getWidth();
        int h = o.getHeight();
        DlgOpciones op = new DlgOpciones(this, true, o);
        op.setVisible(true);
        snake.vel = o.getSpeed().getS();
        opciones = o;
        snake.terminar();
        if(o.getWidth() != w || o.getHeight() != h) {
            actualizaVentana();
        }
        
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void actualizaVentana(){
        this.remove(snake);
        snake = new Snake(opciones.getWidth(), opciones.getHeight(), DefSpeed.NORMAL.getS());
        snake.setPreferredSize(snake.getPreferredSize());
        System.out.println(snake.getPreferredSize());
        add(snake);
        getContentPane().setPreferredSize(snake.getPreferredSize());
        setLocationRelativeTo(null);
        pack();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmSnake.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmSnake.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmSnake.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmSnake.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new frmSnake().setVisible(true);
        });
    }

    @Override
    public void keyTyped(KeyEvent e) {
    }

    @Override
    public void keyPressed(KeyEvent e) {
        if(!snake.hilo.isAlive()){
            snake.comenzar();
        }
        if(!snake.inGame){
            snake.continuar();
            return;
        }
        switch (e.getKeyCode()) {
            case 37: case 65://A, izquierda
                if(snake.dir!=Snake.Dir.R){
                    snake.nextDir = Snake.Dir.L;
                }
                break;
            case 38: case 87://W, arriba
                if(snake.dir!=Snake.Dir.D){
                    snake.nextDir = Snake.Dir.U; 
                }
                break;
            case 39: case 68://D, derecha
                if(snake.dir!=Snake.Dir.L){
                    snake.nextDir = Snake.Dir.R; 
                }
                break;
            case 40: case 83://S, abajo
                if(snake.dir!=Snake.Dir.U){
                    snake.nextDir = Snake.Dir.D;
                }
                break;
        }
    }

    @Override
    public void keyReleased(KeyEvent e) {
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
